#ifndef CAPS_H
#define CAPS_H

#include <stdbool.h>

#include "tyydecl.h"
#include "device.h"

static const lytDeviceCaps ps_caps = {
  .can_unicode = true,
  .can_composite_glyphs = true,
  .can_variable_sizes = true,
  .can_slant = true,
  .can_height_adjust = true,
  .can_abs_pos = true,
  .can_rel_pos = true,
  .can_rules = true,
  .can_lines = true,
  .can_circles = true,
  .can_solid_circles = true,
  .can_ellipses = true,
  .can_solid_ellipses = true,
  .can_polygons = true,
  .can_solid_polygons = true,
  .can_arcs = true,
  .can_splines = true,
  .can_color = true,
  .can_fill = true,
  .can_pattern = true,
  .can_alpha = false,
  .can_embed_file = false,
  .can_embed_image = true,
  .can_specials = true,
  .can_exec_escapes = true,
  .can_page_size = true,
  .can_url_links = false,
  .min_linewidth = 0.01,
  .max_linewidth = 1000.0,
  .min_fontsize = 1.0,
  .max_fontsize = 500.0,
};

static const struct lytDeviceCaps pdf_caps = {
  .can_unicode = true,
  .can_composite_glyphs = true,
  .can_variable_sizes = true,
  .can_slant = true,
  .can_height_adjust = true,
  .can_abs_pos = true,
  .can_rel_pos = true,
  .can_rules = true,
  .can_lines = true,
  .can_circles = true,
  .can_solid_circles = true,
  .can_ellipses = true,
  .can_solid_ellipses = true,
  .can_polygons = true,
  .can_solid_polygons = true,
  .can_arcs = true,
  .can_splines = true,
  .can_color = true,
  .can_fill = true,
  .can_pattern = true,
  .can_alpha = true,
  .can_embed_file = false,
  .can_embed_image = true,
  .can_specials = true,
  .can_exec_escapes = true,
  .can_page_size = true,
  .can_url_links = false,
  .min_linewidth = 0.01,
  .max_linewidth = 1000.0,
  .min_fontsize = 1.0,
  .max_fontsize = 500.0,
};

static const struct lytDeviceCaps dvi_caps = {
    
    .can_unicode           = false,  
    .can_composite_glyphs  = false,  
    .can_variable_sizes    = false,  
    .can_slant             = false,  
    .can_height_adjust     = false,  
    .can_abs_pos           = true,   
    .can_rel_pos           = true,   
    .can_rules             = true,   
    .can_lines             = false,  
    .can_circles           = false,
    .can_solid_circles     = false,
    .can_ellipses          = false,
    .can_solid_ellipses    = false,
    .can_polygons          = false,
    .can_solid_polygons    = false,
    .can_arcs              = false,
    .can_splines           = false,
    .can_color             = false,  
    .can_fill              = false,  
    .can_pattern           = false,
    .can_alpha             = false,
    .can_embed_file        = false,  
    .can_embed_image       = false,  
    .can_specials          = true,   
    .can_exec_escapes      = false,  
    .can_page_size         = false,  
    .can_url_links         = false,  
    .min_linewidth         = 0.0,    
    .max_linewidth         = 32767.0,
    .min_fontsize          = 1.0,    
    .max_fontsize          = 1000.0  
};


static const struct lytDeviceCaps utf8_caps = {
    .can_unicode           = true,   
    .can_composite_glyphs  = true,   
    .can_variable_sizes    = false,  
    .can_slant             = false,  
    .can_height_adjust     = false,  
    .can_abs_pos           = false,  
    .can_rel_pos           = true,   
    .can_rules             = false,  
    .can_lines             = false,
    .can_circles           = false,
    .can_solid_circles     = false,
    .can_ellipses          = false,
    .can_solid_ellipses    = false,
    .can_polygons          = false,
    .can_solid_polygons    = false,
    .can_arcs              = false,
    .can_splines           = false,
    .can_color             = false,  
    .can_fill              = false,
    .can_pattern           = false,
    .can_alpha             = false,
    .can_embed_file        = false,
    .can_embed_image       = false,
    .can_specials          = true,   
    .can_exec_escapes      = false,  
    .can_page_size         = false,
    .can_url_links         = false,
    .min_linewidth         = 1.0,    
    .max_linewidth         = 1.0,
    .min_fontsize          = 1.0,    
    .max_fontsize          = 1.0
};

static const struct lytDeviceCaps ascii_caps = {
    .can_unicode           = false,  
    .can_composite_glyphs  = false,  
    .can_variable_sizes    = false,
    .can_slant             = false,
    .can_height_adjust     = false,
    .can_abs_pos           = false,
    .can_rel_pos           = true,   
    .can_rules             = false,
    .can_lines             = false,
    .can_circles           = false,
    .can_solid_circles     = false,
    .can_ellipses          = false,
    .can_solid_ellipses    = false,
    .can_polygons          = false,
    .can_solid_polygons    = false,
    .can_arcs              = false,
    .can_splines           = false,
    .can_color             = false,
    .can_fill              = false,
    .can_pattern           = false,
    .can_alpha             = false,
    .can_embed_file        = false,
    .can_embed_image       = false,
    .can_specials          = true,   
    .can_exec_escapes      = false,
    .can_page_size         = false,
    .can_url_links         = false,
    .min_linewidth         = 1.0,
    .max_linewidth         = 1.0,
    .min_fontsize          = 1.0,
    .max_fontsize          = 1.0
};


#endif

